# Change the default theme to be used when building the site with Hugo
theme = "hugo-theme-learn"

# Base URL for the site
baseURL = "https://v2d27.github.io/aws-fcj/"  # Replace with your actual GitHub Pages URL or domain

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = "https://v2d27.github.io/aws-fcj/"
  description = "AWS Site-to-Site VPN"
  author = "ducduc08@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  hideEditLink = true

  
[Languages]
[Languages.en]
title = "AWS Site-to-Site VPN"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Site-to-Site VPN workshop"
identifier = "AWS Workshop"
url = "https://github.com/v2d27/aws-fcj/"
weight = 21


