name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build the site
        run: hugo --minify --destination ./public/ws1  # Output to a subfolder

  deploy:
    environment:
      name: github-pages
      url: "https://v2d27.github.io/aws-fcj-ws/ws1/"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./public/ws1  # Specify the subfolder where the site is built
          publish_branch: gh-pages  # Set to the branch where you want to deploy
